### ISSUE TITLE
titleMaxLine in settingsTile does not work on iOS

### ISSUE THREAD

**Issue by lordvidex** [yako-dev/flutter-settings-ui#59]
the settingsTile widget still shows '...' after long text even when maxLine was set to 2 but this works on Android

**Comment by yadaniyil** [comment]
Should be fixed in the ^1.0.0 version. Please check and reopen if it's not working.

**Comment by scottishstoater** [comment]
@yadaniyil This is still not working on ^1.0.0. 

```dart
SettingsSection(
  title: 'Misc',
  tiles: [
    SettingsTile(
        title: 'Manage Consent Preferences', 
        leading: const Icon(Icons.description), 
        onTap: () {
          // ...
      }
    ),
    SettingsTile(
        title: 'Open source licenses',
        titleMaxLines: 10,
        trailing: null,
        leading: Icon(Icons.collections_bookmark)),
  ],
),
```

<img width="539" alt="Screenshot 2021-12-03 at 11 31 47" src="https://user-images.githubusercontent.com/6320793/144595760-739c32e1-6e72-495d-8404-fd02b3139b59.png">
